import React, { useMemo, useState } from 'react';
import { formatDate, formatDuration } from '../lib/i18n';

function Heading({ eyebrow, title, text, action }) {
  return <section className="page-heading"><div className="page-heading-copy"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{text && <p>{text}</p>}</div>{action}</section>;
}

function PuzzleCard({ puzzle, status, t, master, home = false, onDelete }) {
  const gameType = puzzle.gameType || (puzzle.format === 'spl' ? 'spiral' : 'crossword');
  const isCompleted = status?.status === 'completed';
  const isStarted = status?.status === 'started';
  if (home) return <article className="puzzle-list-item"><div className="puzzle-list-dimension">{puzzle.width}×{puzzle.height}</div><div className="puzzle-list-content"><h3><a href={`/jokoak/game/${puzzle._id}`}>{puzzle.name}</a></h3><p className="puzzle-author">{puzzle.author || t('common.unknownAuthor')}</p></div><div className="puzzle-list-meta"><span className="puzzle-new">{t('home.new')}</span><span>{formatDate(puzzle.createdAt)}</span></div><a className="btn btn-primary btn-sm" href={`/jokoak/game/${puzzle._id}`} aria-label={t('home.playAria', { name: puzzle.name })}>{t('common.play')}</a></article>;
  return <article className="puzzle-list-item"><div className="puzzle-list-dimension">{puzzle.width}×{puzzle.height}</div><div className="puzzle-list-content"><h2><a href={`/jokoak/game/${puzzle._id}`}>{puzzle.name}</a></h2><p className="puzzle-author">{puzzle.author || t('common.unknownAuthor')}</p><div className="puzzle-list-details"><span className={`game-type-pill${gameType === 'spiral' ? ' game-type-pill--spiral' : ''}`}>{gameType === 'spiral' ? t('catalog.spiralType') : t('catalog.crosswordType')}</span>{isCompleted ? <><span>✓ {formatDuration(status.elapsedSeconds)}</span><span>{status.errorCount ? (status.errorCount === 1 ? t('catalog.oneError') : `${status.errorCount} ${t('catalog.errors')}`) : (!status.usedVerify && !status.usedHints ? t('catalog.perfect') : '')}</span></> : <span>{isStarted ? t('catalog.savedGame') : t('catalog.ready')}</span>}<span>{formatDate(puzzle.createdAt)}</span></div></div><div className="puzzle-list-status"><span className={`status-pill${isCompleted ? ' status-pill--complete' : isStarted ? ' status-pill--progress' : ''}`}>{isCompleted ? t('catalog.completed') : isStarted ? t('catalog.inProgress') : t('catalog.notStarted')}</span></div><div className="puzzle-list-actions"><a className="btn btn-primary" href={`/jokoak/game/${puzzle._id}`}>{isStarted ? t('common.continue') : t('common.play')}</a>{master && <button className="btn btn-outline-danger" onClick={() => onDelete(puzzle)}>{t('common.delete')}</button>}</div></article>;
}

export function HomePage({ puzzles = [], user, t }) {
  const cells = ['H', 'I', 'T', 'Z', '', 'G', 'U', 'R', 'U', 'T', 'Z', '', 'A', 'K', ''];
  return <><section className="hero"><div className="hero-copy"><p className="eyebrow">{t('home.eyebrow')}</p><h1>{t('home.title')}</h1><p className="hero-text">{t('home.intro')}</p><div className="hero-actions"><a className="btn btn-primary btn-lg" href="/jokoak">{t('home.browse')}</a>{!user && <a className="btn btn-outline-light btn-lg" href="/users/register">{t('nav.createAccount')}</a>}</div></div><div className="hero-panel" aria-hidden="true"><div className="hero-grid">{cells.map((cell, index) => <span className={`hero-cell${cell ? '' : ' hero-cell--dark'}`} key={index}>{cell}</span>)}</div></div></section><section className="section-heading"><div className="section-heading-copy"><p className="eyebrow">{t('home.latestEyebrow')}</p><h2>{t('home.latest')}</h2></div><a className="section-link" href="/jokoak">{t('home.allCatalog')}</a></section>{puzzles.length ? <div className="puzzle-list">{puzzles.map(puzzle => <PuzzleCard key={puzzle._id} puzzle={puzzle} t={t} home />)}</div> : <div className="empty-state"><h2>{t('home.emptyTitle')}</h2><p>{t('home.emptyText')}</p></div>}</>;
}

export function PuzzlesPage({ puzzles = [], statusMap = {}, user, t }) {
  const [search, setSearch] = useState(''); const [type, setType] = useState('all'); const [status, setStatus] = useState('all');
  const [items, setItems] = useState(puzzles);
  const visible = useMemo(() => items.filter(puzzle => {
    const gameType = puzzle.gameType || (puzzle.format === 'spl' ? 'spiral' : 'crossword'); const gameStatus = statusMap[puzzle._id]?.status || 'notstarted';
    return `${puzzle.name} ${puzzle.author || ''}`.toLocaleLowerCase('eu').includes(search.toLocaleLowerCase('eu')) && (type === 'all' || type === gameType) && (status === 'all' || status === gameStatus);
  }), [items, search, type, status, statusMap]);
  const deletePuzzle = async puzzle => {
    if (!window.confirm(t('client.deleteConfirm', { name: puzzle.name }))) return;
    const response = await fetch(`/jokoak/game/${puzzle._id}`, { method: 'DELETE' });
    if (response.ok) setItems(current => current.filter(item => item._id !== puzzle._id)); else window.alert(t('client.deleteFailed'));
  };
  return <><Heading eyebrow={t('catalog.eyebrow')} title={t('catalog.title')} text={t('catalog.intro')} action={user?.master && <a className="btn btn-outline-primary" href="/jokoak/upload">{t('catalog.upload')}</a>} />{user?.master && <aside className="admin-note"><strong>{t('catalog.adminMode')}</strong> {t('catalog.adminText')}</aside>}{!items.length ? <div className="empty-state"><h2>{t('catalog.emptyTitle')}</h2><p>{user?.master ? t('catalog.emptyAdmin') : t('catalog.emptyPlayer')}</p>{user?.master && <a className="btn btn-primary" href="/jokoak/upload">{t('catalog.upload')}</a>}</div> : <><div className="catalog-controls"><label className="search-field"><span>{t('catalog.search')}</span><input className="form-control" type="search" value={search} placeholder={t('catalog.searchPlaceholder')} onChange={event => setSearch(event.target.value)} /></label><label className="filter-field"><span>{t('catalog.type')}</span><select className="form-control" value={type} onChange={event => setType(event.target.value)}><option value="all">{t('common.all')}</option><option value="crossword">{t('catalog.crosswordType')}</option><option value="spiral">{t('catalog.spiralType')}</option></select></label>{user && <label className="filter-field"><span>{t('catalog.status')}</span><select className="form-control" value={status} onChange={event => setStatus(event.target.value)}><option value="all">{t('common.all')}</option><option value="started">{t('catalog.inProgress')}</option><option value="completed">{t('catalog.completed')}</option><option value="notstarted">{t('catalog.notStarted')}</option></select></label>}<p className="catalog-count">{t('client.puzzleCount', { count: visible.length })}</p></div><div className="puzzle-list">{visible.map(puzzle => <PuzzleCard key={puzzle._id} puzzle={puzzle} status={statusMap[puzzle._id]} t={t} master={user?.master} onDelete={deletePuzzle} />)}</div></>}</>;
}

function AuthPage({ register, errors = [], t }) {
  const prefix = register ? 'register' : 'login';
  return <section className="auth-layout"><div className="auth-intro"><p className="eyebrow">{t(`auth.${prefix}Eyebrow`)}</p><h1>{t(`auth.${prefix}Title`)}</h1><p>{t(`auth.${prefix}Text`)}</p></div><div className="auth-card"><h2>{register ? t('nav.createAccount') : t('auth.login')}</h2>{errors.map(error => <div className="alert alert-danger" key={error.param}>{error.msg}</div>)}<form className="auth-form" method="POST" action={register ? '/users/register' : '/users/login'}>{register && <div className="form-group"><label htmlFor="email">{t('auth.email')}</label><input id="email" className="form-control" name="email" type="email" autoComplete="email" required /></div>}<div className="form-group"><label htmlFor="username">{t('auth.username')}</label><input id="username" className="form-control" name="username" type="text" autoComplete="username" minLength={register ? 3 : undefined} maxLength={register ? 40 : undefined} required autoFocus />{register && <small className="form-hint">{t('auth.usernameHint')}</small>}</div><div className="form-group"><label htmlFor="password">{t('auth.password')}</label><input id="password" className="form-control" name="password" type="password" autoComplete={register ? 'new-password' : 'current-password'} minLength={register ? 4 : undefined} required />{register && <small className="form-hint">{t('auth.passwordHint')}</small>}</div>{register && <div className="form-group"><label htmlFor="password2">{t('auth.repeatPassword')}</label><input id="password2" className="form-control" name="password2" type="password" autoComplete="new-password" required /></div>}<button className="btn btn-primary btn-block" type="submit">{register ? t('nav.createAccount') : t('auth.enter')}</button></form><p className="auth-footer">{register ? t('auth.haveAccount') : t('auth.noAccount')} <a href={register ? '/users/login' : '/users/register'}>{register ? t('nav.signIn') : t('nav.createAccount')}</a></p></div></section>;
}

export const LoginPage = props => <AuthPage {...props} />;
export const RegisterPage = props => <AuthPage {...props} register />;

export function DashboardPage({ stats, completed = [], inProgress = [], t }) { return <div className="dashboard"><Heading eyebrow={t('dashboard.eyebrow')} title={t('dashboard.title')} text={t('dashboard.intro')} action={<a className="btn btn-outline-primary" href="/jokoak">{t('home.browse')}</a>} /><div className="dashboard-stats-row">{[[stats.completed, t('dashboard.completed')], [stats.inProgress, t('dashboard.inProgress')], [stats.total, t('dashboard.all')]].map(([value, label]) => <div className="stat-card" key={label}><div className="stat-value">{value}</div><div className="stat-label">{label}</div></div>)}</div>{completed.length > 0 && <SessionTable title={`✓ ${t('dashboard.completed')}`} sessions={completed} completed t={t} />}{inProgress.length > 0 && <SessionTable title={`⏳ ${t('dashboard.inProgress')}`} sessions={inProgress} t={t} />}{!completed.length && !inProgress.length && <><p className="text-muted">{t('dashboard.empty')}</p><a className="btn btn-primary" href="/jokoak">{t('dashboard.viewPuzzles')}</a></>}</div>; }

function SessionTable({ title, sessions, completed, t }) { return <><h2 className="dashboard-section-title">{title}</h2><table className="table table-sm table-hover"><thead><tr><th>{t('common.name')}</th><th>{t('common.size')}</th><th>{completed ? t('dashboard.completedAt') : t('dashboard.startedAt')}</th>{completed && <th>{t('dashboard.duration')}</th>}<th /></tr></thead><tbody>{sessions.map(session => <tr key={session._id}><td>{completed ? <a href={`/jokoak/game/${session.puzzleId}`}>{session.puzzle?.name || session.puzzleId}</a> : session.puzzle?.name || session.puzzleId}</td><td>{session.puzzle ? `${session.puzzle.width}×${session.puzzle.height}` : '—'}</td><td>{formatDate(completed ? session.completedAt : session.startedAt)}</td>{completed && <td>{session.durationSeconds == null ? '—' : formatDuration(session.durationSeconds)}</td>}<td>{!completed && <a className="btn btn-sm btn-outline-primary" href={`/jokoak/game/${session.puzzleId}`}>{t('common.continue')}</a>}</td></tr>)}</tbody></table></>; }

export function UploadPage({ user, t }) { return <section className="form-page"><Heading eyebrow={t('upload.eyebrow')} title={t('upload.title')} text={t('upload.intro')} action={<div className="page-actions">{user?.master && <a className="btn btn-outline-secondary" href="/jokoak/spiral-builder">{t('upload.builder')}</a>}<a className="btn btn-outline-primary" href="/jokoak">{t('upload.backToCatalog')}</a></div>} /><div className="upload-card"><form className="auth-form" method="POST" action="/jokoak/upload" encType="multipart/form-data"><div className="form-group"><label htmlFor="filename">{t('upload.file')}</label><input id="filename" className="form-control" name="filename" type="file" accept=".ipuz,.puz,.spl" required /><small className="form-hint">{t('upload.hint')}</small></div><button className="btn btn-primary" type="submit">{t('upload.submit')}</button></form></div></section>; }

export function MasterPage({ stats, puzzles = [], users = [], completionMap = {}, userStats = {}, recentCompletions = [], downloadsFiles = [], t }) { return <div className="dashboard"><Heading eyebrow={t('upload.eyebrow')} title={t('master.title')} text={t('master.intro')} /><div className="dashboard-stats-row">{[[stats.puzzles, t('master.puzzleCount')], [stats.users, t('master.userCount')], [stats.completions, t('master.completionCount')], [stats.activeSessions, t('common.active')]].map(([value, label]) => <div className="stat-card" key={label}><div className="stat-value">{value}</div><div className="stat-label">{label}</div></div>)}</div><div className="dashboard-actions"><a className="btn btn-primary" href="/jokoak/upload">{t('master.upload')}</a></div><h2 className="dashboard-section-title">{t('master.externalApi')}</h2><div className="card mb-4"><div className="card-body"><p className="mb-2">{t('master.apiDescription')}</p><p className="mb-0 text-muted">{t('master.apiSecret')}</p></div></div><h2 className="dashboard-section-title">{t('master.downloads')}</h2>{downloadsFiles.length ? <table className="table table-sm"><thead><tr><th>{t('common.name')}</th><th>{t('common.size')}</th><th>{t('common.date')}</th></tr></thead><tbody>{downloadsFiles.map(file => <tr key={file.name}><td><a href={`/master/download/${encodeURIComponent(file.name)}`}>{file.name}</a></td><td>{file.sizeDisplay}</td><td>{file.mtimeDisplay}</td></tr>)}</tbody></table> : <p className="text-muted">{t('master.downloadsEmpty')}</p>}<MasterTables puzzles={puzzles} users={users} completionMap={completionMap} userStats={userStats} recentCompletions={recentCompletions} t={t} /></div>; }

function MasterTables({ puzzles, users, completionMap, userStats, recentCompletions, t }) { return <><h2 className="dashboard-section-title">{t('nav.puzzles')}</h2><table className="table table-sm table-hover"><thead><tr><th>{t('common.name')}</th><th>{t('common.size')}</th><th>{t('common.author')}</th><th>{t('master.completionCountShort')}</th><th>{t('master.published')}</th><th /></tr></thead><tbody>{puzzles.map(puzzle => <tr key={puzzle._id}><td>{puzzle.name}</td><td>{puzzle.width}×{puzzle.height}</td><td>{puzzle.author || '—'}</td><td>{completionMap[puzzle._id] || 0}</td><td>{formatDate(puzzle.createdAt)}</td><td><a className="btn btn-sm btn-outline-secondary" href={`/jokoak/game/${puzzle._id}`}>{t('common.play')}</a></td></tr>)}</tbody></table><h2 className="dashboard-section-title">{t('master.users')}</h2><table className="table table-sm table-hover"><thead><tr><th>{t('auth.username')}</th><th>{t('common.authorEmail')}</th><th>{t('common.manager')}</th><th>{t('dashboard.completed')}</th><th>{t('common.active')}</th></tr></thead><tbody>{users.map(user => <tr key={user._id}><td>{user.username}</td><td>{user.email}</td><td>{user.master && <span className="badge badge-warning">{t('common.authorized')}</span>}</td><td>{userStats[user._id]?.completed || 0}</td><td>{userStats[user._id]?.inProgress || 0}</td></tr>)}</tbody></table><h2 className="dashboard-section-title">{t('master.recentCompletions', { count: recentCompletions.length })}</h2><table className="table table-sm"><thead><tr><th>{t('auth.username')}</th><th>{t('nav.puzzles')}</th><th>{t('common.date')}</th></tr></thead><tbody>{recentCompletions.map(session => <tr key={session._id}><td>{session.username || session.userId}</td><td>{session.puzzleName || session.puzzleId}</td><td>{formatDate(session.completedAt)}</td></tr>)}</tbody></table></>; }

export function MessagePage({ message, type }) { return <div className={`alert alert-${type}`}>{message}</div>; }
export function NotFoundPage({ url, t }) { return <section className="empty-state error-state"><p className="eyebrow">{t('notFound.eyebrow')}</p><h1>{t('notFound.title')}</h1><p>{t('notFound.text', { url })}</p><a className="btn btn-primary" href="/jokoak">{t('dashboard.viewPuzzles')}</a></section>; }
